function perf_arr = ...
    classifier_performance( ...
    i_max, ...
    rp, ...
    rs, ...
    ks, ...
    p_obs ...
    )

[C_pp, C_ps] = prim_classifier_prob(i_max,rp,p_obs);
[C_sp, C_ss] = sec_classifier_prob(i_max,rp,rs,ks,p_obs);

perf_p = ((1-rs)*C_pp)/((1-rs)*C_pp + rs*C_sp);
perf_s = rs*C_ss/(rs*C_ss + (1-rs)*C_ps);
accur = (rs*C_ss + (1-rs)*C_pp)/p_obs;
r_inf = ((1-rs)*C_ps + rs*C_ss)/p_obs;
r_bias = r_inf - rs;

perf_arr = [C_pp C_ps C_sp, C_ss perf_p perf_s accur r_inf r_bias];