function  rs_inf_res = compatible_par_inf( ...
    imax, ...
    rs_obs, ...
    rp_arr, ...
    ks, ...
    p_obs_arr, ...
    ofile ...
    )

rs_inf_res = zeros(length(rp_arr),length(p_obs_arr));
for ss = 1:length(rp_arr)
    for pp = 1:length(p_obs_arr)
        % [rp_arr(ss) p_obs_arr(pp)]
        fprintf("%f\t", rp_arr(ss))
        fprintf("%f\n", p_obs_arr(pp))
        % what Rs value gives zero Rsinf
        rs_inf_res(ss,pp) = fzero(@(x) ...
            (det_rs_inf(imax, rp_arr(ss),x,ks,p_obs_arr(pp)) ...
            - rs_obs), 0.5,optimset('TolX',.01));
    end
end

save(ofile)