%%
i_max = 800;
rp_arr = 1:.1:2;
rs_arr = [0.2 0.8];
ks_arr = [0.3 1e3];
p_obs_arr = 0.1:0.1:1;

% Theory
res_arr = sample_classifer( ...
    i_max, ...
    rp_arr, ...
    rs_arr, ...
    ks_arr, ...
    p_obs_arr, ...
    'data/011119_rp_pobs' ...
    );

%%
% Observed OR example
clear;
k = 0.3;
rp_arr = 1:.1:2;
p_obs_arr = .25:.05:1;
rs_arr = [0.25, 0.5 0.75];
inc_arr = [0.8 0.5; 0.5 0.2; 0.1 0.027027];

gen_ORx_data( ...
    rp_arr, ...
    p_obs_arr, ...
    rs_arr, ...
    inc_arr, ...
    k, ...
    'data/040419_ORx_example' ...
    )

%% mpox 1980s
% Primary infection: Male 142 Female 103
% Secondary infection: Male 40 Female 53

clear;
k_mpx = 0.3;
Compat_arr = compatible_par_inf( ...
    800, ...
    93/338, ...
    1:.05:1.3, ...
    k_mpx, ...
    0.25:.05:1, ...
    'data/111925_mpx_r' ...
    );

clear
d_mpx = load('data/111925_mpx_r');

rp_num = length(d_mpx.rp_arr);
po_num = length(d_mpx.p_obs_arr);
res_arr = zeros(rp_num,po_num,13);
k_mpx = 0.3;
for pp = 1:rp_num
    for oo = 1:po_num
        [pp rp_num oo po_num]
        res_arr(pp,oo,1:9) = classifier_performance( ...
            800, d_mpx.rp_arr(pp), d_mpx.rs_inf_res(pp,oo), k_mpx, d_mpx.p_obs_arr(oo) ...
            );
        % Treating female as 'positive'
        res_arr(pp,oo,10:13) = OR_performance( ...
            d_mpx.p_obs_arr(oo), ...
            res_arr(pp,oo,1), res_arr(pp,oo,2), res_arr(pp,oo,3), res_arr(pp,oo,4), ...
            142/338, 103/338, 40/338, 53/338 ... % X_pn, X_pp, X_sn, X_sp
            );
    end
end

save('data/111925_1980s_mpx_OR')

%% mpox 2010s

clear;
k_mpox = 0.3;
Compat_arr = compatible_par_inf( ...
    800, ...
    533/829, ... % 1 - primary/total = secondary/total
    1:.05:1.5, ...
    k_mpox, ...
    0.25:.05:1, ...
    'data/082225_mpox_r' ...
    );

clear;
d_mpox = load('data/082225_mpox_r');

rp_num = length(d_mpox.rp_arr);
po_num = length(d_mpox.p_obs_arr);
res_arr = zeros(rp_num,po_num,13);
k_mpox = 0.3;
for pp = 1:rp_num
    for oo = 1:po_num
        [pp rp_num oo po_num]
        res_arr(pp,oo,1:9) = classifier_performance( ...
            800, d_mpox.rp_arr(pp), d_mpox.rs_inf_res(pp,oo), k_mpox, d_mpox.p_obs_arr(oo) ...
            );
        % Treating contact with animals as 'positive'
        res_arr(pp,oo,10:13) = OR_performance( ...
            d_mpox.p_obs_arr(oo), ...
            res_arr(pp,oo,1), res_arr(pp,oo,2), res_arr(pp,oo,3), res_arr(pp,oo,4), ...
            135/829, 161/829, 295/829, 238/829 ... % X_pn, X_pp, X_sn, X_sp
            );
        % res_arr(pp,oo,13)
    end
end

save('data/082225_2010s_mpox_OR')

