%{
Accepted-paper simulation settings:
True R_s = 0.50
k_s = 0.30
True OR = 2.00
Simulations per sample size = 100
Numbers of clusters = [100 200 300 400 500 600 700 800 900 1000]

The figures folder contains the six-panel Figure S.2 and the three separate two-panel scenario figures.


%}

function generate_figure_S2_sample_size_validation()

clc;
close all;

sourceBase = mfilename('fullpath');

if isempty(sourceBase)
    error('Save this MATLAB file before running it.');
end

sourceFile = [sourceBase, '.m'];
sourceFolder = fileparts(sourceFile);

packageName = 'Figure_S2_Sample_Size_Validation';
[~, currentFolderName] = fileparts(sourceFolder);

if strcmpi(currentFolderName, packageName)
    packageFolder = sourceFolder;
else
    packageFolder = fullfile(sourceFolder, packageName);
end

figuresFolder = fullfile(packageFolder, 'figures');
resultsFolder = fullfile(packageFolder, 'data');

create_folder(packageFolder);
create_folder(figuresFolder);
create_folder(resultsFolder);

clear_folder_files(figuresFolder);
clear_folder_files(resultsFolder);

packageCode = fullfile( ...
    packageFolder, ...
    'generate_figure_S2_sample_size_validation.m');

if ~strcmpi(sourceFile, packageCode)

    if exist(packageCode, 'file')
        delete(packageCode);
    end

    [copySuccess, copyMessage] = copyfile(sourceFile, packageCode);

    if ~copySuccess
        error('Could not copy the MATLAB file: %s', copyMessage);
    end
end

rng(1, 'twister');

Rs = 0.5;
ks = 0.3;

Ip = 2/3;
Is = 0.5;

trueOR = ...
    (Ip * (1 - Is)) / ...
    ((1 - Ip) * Is);

numRuns = 200;
clusterNumbers = 100:100:1000;

iMax = 500;
rsGrid = linspace(0.001, 0.95, 900);

secondaryPrecomputation = ...
    make_secondary_precomputation(iMax, ks);

scenarios = struct( ...
    'id', {2, 3, 4}, ...
    'name', { ...
        'Imperfect observation only', ...
        'Overlapping transmission chains only', ...
        'Imperfect observation and overlapping transmission chains'}, ...
    'fileName', { ...
        'Scenario_2_Imperfect_Observation_Only', ...
        'Scenario_3_Overlapping_Transmission_Chains_Only', ...
        'Scenario_4_Imperfect_Observation_and_Overlap'}, ...
    'Rp', {1.0, 1.5, 1.5}, ...
    'pObs', {0.5, 1.0, 0.5}, ...
    'RsLimits', { ...
        [0.25, 0.70], ...
        [0.30, 0.70], ...
        [0.30, 0.65]}, ...
    'ORLimits', { ...
        [0, 5], ...
        [0, 5], ...
        [0, 5]});

fprintf('\n');
fprintf('============================================================\n');
fprintf('FIGURE S.2 SAMPLE-SIZE VALIDATION STARTED\n');
fprintf('============================================================\n');
fprintf('Output folder:\n%s\n\n', packageFolder);
fprintf('True R_s                     = %.2f\n', Rs);
fprintf('Dispersion parameter, k_s   = %.2f\n', ks);
fprintf('Trait probability, I_p      = %.4f\n', Ip);
fprintf('Trait probability, I_s      = %.4f\n', Is);
fprintf('True odds ratio             = %.2f\n', trueOR);
fprintf('Simulations per sample size = %d\n', numRuns);
fprintf('Numbers of clusters         = %s\n', ...
    mat2str(clusterNumbers));
fprintf('============================================================\n\n');

allResults = cell(numel(scenarios), 1);
summaryTables = cell(numel(scenarios), 1);

for scenarioIndex = 1:numel(scenarios)

    scenario = scenarios(scenarioIndex);

    fprintf('------------------------------------------------------------\n');
    fprintf('Scenario %d: %s\n', ...
        scenario.id, scenario.name);
    fprintf('R_p = %.2f, p_obs = %.2f\n', ...
        scenario.Rp, scenario.pObs);
    fprintf('Preparing analytical lookup...\n');

    lookup = precompute_analytical_lookup( ...
        iMax, ...
        scenario.Rp, ...
        ks, ...
        scenario.pObs, ...
        rsGrid, ...
        secondaryPrecomputation);

    numberOfSampleSizes = numel(clusterNumbers);

    naiveRsRuns = NaN(numberOfSampleSizes, numRuns);
    correctedRsRuns = NaN(numberOfSampleSizes, numRuns);
    naiveORRuns = NaN(numberOfSampleSizes, numRuns);
    correctedORRuns = NaN(numberOfSampleSizes, numRuns);

    for sampleIndex = 1:numberOfSampleSizes

        numberOfClusters = clusterNumbers(sampleIndex);

        fprintf('  Simulating %4d clusters: ', ...
            numberOfClusters);

        for runIndex = 1:numRuns

            summary = simulate_observed_summary( ...
                numberOfClusters, ...
                scenario.Rp, ...
                Rs, ...
                ks, ...
                scenario.pObs, ...
                Ip, ...
                Is);

            if summary.totalObserved < 5
                continue;
            end

            naiveRs = summary.naiveRs;

            correctedRs = infer_corrected_Rs( ...
                naiveRs, lookup);

            Cpp = lookup.Cpp;
            Cps = lookup.Cps;

            Csp = interp1( ...
                lookup.rsGrid, ...
                lookup.CspGrid, ...
                correctedRs, ...
                'linear', ...
                'extrap');

            Css = interp1( ...
                lookup.rsGrid, ...
                lookup.CssGrid, ...
                correctedRs, ...
                'linear', ...
                'extrap');

            Xpp = ...
                summary.primaryPositive / ...
                summary.totalObserved;

            Xpn = ...
                summary.primaryNegative / ...
                summary.totalObserved;

            Xsp = ...
                summary.secondaryPositive / ...
                summary.totalObserved;

            Xsn = ...
                summary.secondaryNegative / ...
                summary.totalObserved;

            trueProbabilities = recover_true_probabilities( ...
                scenario.pObs, ...
                Cpp, ...
                Cps, ...
                Csp, ...
                Css, ...
                Xpn, ...
                Xpp, ...
                Xsn, ...
                Xsp);

            correctedOR = NaN;

            if all(isfinite(trueProbabilities)) && ...
                    all(trueProbabilities > 0)

                candidateOR = ...
                    (trueProbabilities(2) * ...
                    trueProbabilities(3)) / ...
                    (trueProbabilities(1) * ...
                    trueProbabilities(4));

                if isfinite(candidateOR) && ...
                        isreal(candidateOR) && ...
                        candidateOR > 0

                    correctedOR = candidateOR;
                end
            end

            naiveRsRuns(sampleIndex, runIndex) = ...
                naiveRs;

            correctedRsRuns(sampleIndex, runIndex) = ...
                correctedRs;

            naiveORRuns(sampleIndex, runIndex) = ...
                summary.naiveOR;

            correctedORRuns(sampleIndex, runIndex) = ...
                correctedOR;
        end

        validRs = sum(isfinite( ...
            correctedRsRuns(sampleIndex, :)));

        validOR = sum(isfinite( ...
            correctedORRuns(sampleIndex, :)));

        fprintf(['completed. Valid runs: ', ...
            'R_s = %d/%d, OR = %d/%d\n'], ...
            validRs, numRuns, validOR, numRuns);
    end

    result = struct();

    result.scenarioID = scenario.id;
    result.scenarioName = scenario.name;
    result.Rp = scenario.Rp;
    result.pObs = scenario.pObs;

    result.medianNaiveRs = ...
        row_percentile(naiveRsRuns, 50);

    result.medianCorrectedRs = ...
        row_percentile(correctedRsRuns, 50);

    result.correctedRsLower95 = ...
        row_percentile(correctedRsRuns, 2.5);

    result.correctedRsUpper95 = ...
        row_percentile(correctedRsRuns, 97.5);

    result.medianNaiveOR = ...
        row_percentile(naiveORRuns, 50);

    result.medianCorrectedOR = ...
        row_percentile(correctedORRuns, 50);

    result.correctedORLower95 = ...
        row_percentile(correctedORRuns, 2.5);

    result.correctedORUpper95 = ...
        row_percentile(correctedORRuns, 97.5);

    result.validCorrectedRsRuns = ...
        sum(isfinite(correctedRsRuns), 2);

    result.validCorrectedORRuns = ...
        sum(isfinite(correctedORRuns), 2);

    result.naiveRsRuns = naiveRsRuns;
    result.correctedRsRuns = correctedRsRuns;
    result.naiveORRuns = naiveORRuns;
    result.correctedORRuns = correctedORRuns;

    allResults{scenarioIndex} = result;

    summaryTable = table( ...
        repmat(scenario.id, numberOfSampleSizes, 1), ...
        repmat({scenario.name}, numberOfSampleSizes, 1), ...
        repmat(scenario.Rp, numberOfSampleSizes, 1), ...
        repmat(scenario.pObs, numberOfSampleSizes, 1), ...
        repmat(numRuns, numberOfSampleSizes, 1), ...
        clusterNumbers(:), ...
        result.medianNaiveRs, ...
        result.medianCorrectedRs, ...
        result.correctedRsLower95, ...
        result.correctedRsUpper95, ...
        result.medianNaiveOR, ...
        result.medianCorrectedOR, ...
        result.correctedORLower95, ...
        result.correctedORUpper95, ...
        result.validCorrectedRsRuns, ...
        result.validCorrectedORRuns, ...
        'VariableNames', { ...
        'ScenarioID', ...
        'ScenarioName', ...
        'Rp', ...
        'p_obs', ...
        'SimulationRuns', ...
        'NumberOfClusters', ...
        'MedianNaiveRs', ...
        'MedianCorrectedRs', ...
        'CorrectedRsLower95', ...
        'CorrectedRsUpper95', ...
        'MedianNaiveOR', ...
        'MedianCorrectedOR', ...
        'CorrectedORLower95', ...
        'CorrectedORUpper95', ...
        'ValidCorrectedRsRuns', ...
        'ValidCorrectedORRuns'});

    summaryTables{scenarioIndex} = summaryTable;

    writetable( ...
        summaryTable, ...
        fullfile( ...
            resultsFolder, ...
            [scenario.fileName, '_Summary.csv']));

    scenarioResult = result;

    save( ...
        fullfile( ...
            resultsFolder, ...
            [scenario.fileName, '_Results.mat']), ...
        'scenarioResult', ...
        'clusterNumbers', ...
        'Rs', ...
        'ks', ...
        'Ip', ...
        'Is', ...
        'trueOR', ...
        'numRuns');

    figureHandle = make_scenario_figure( ...
        clusterNumbers, ...
        result, ...
        Rs, ...
        trueOR, ...
        scenario);

    figureBase = fullfile( ...
        figuresFolder, ...
        scenario.fileName);

    save_figure( ...
        figureHandle, ...
        [figureBase, '.png'], ...
        [figureBase, '.jpg'], ...
        [figureBase, '.pdf']);

    close(figureHandle);

    fprintf('Scenario %d saved successfully.\n\n', ...
        scenario.id);
end

allScenariosTable = vertcat(summaryTables{:});

writetable( ...
    allScenariosTable, ...
    fullfile( ...
        resultsFolder, ...
        'All_Scenarios_Summary.csv'));

matlabVersion = version;
generationTime = datestr(now, 30);

save( ...
    fullfile( ...
        resultsFolder, ...
        'All_Scenarios_Complete_Results.mat'), ...
    'allResults', ...
    'scenarios', ...
    'clusterNumbers', ...
    'Rs', ...
    'ks', ...
    'Ip', ...
    'Is', ...
    'trueOR', ...
    'numRuns', ...
    'matlabVersion', ...
    'generationTime');

readmeFile = fullfile(packageFolder, 'README.md');

write_readme( ...
    readmeFile, ...
    numRuns, ...
    clusterNumbers, ...
    Rs, ...
    ks, ...
    Ip, ...
    Is, ...
    trueOR);

packageParent = fileparts(packageFolder);

zipFile = fullfile( ...
    packageParent, ...
    [packageName, '.zip']);

if exist(zipFile, 'file')
    delete(zipFile);
end

originalFolder = pwd;

try

    cd(packageParent);
    zip(zipFile, packageName);
    cd(originalFolder);

catch zipError

    cd(originalFolder);

    warning('Could not create ZIP file: %s', ...
        zipError.message);
end

fprintf('\n');
fprintf('============================================================\n');
fprintf('FIGURE S.2 SAMPLE-SIZE VALIDATION COMPLETED\n');
fprintf('============================================================\n');
fprintf('Package folder:\n%s\n\n', packageFolder);

for scenarioIndex = 1:numel(scenarios)

    fprintf('Scenario %d figure:\n%s\n\n', ...
        scenarios(scenarioIndex).id, ...
        fullfile( ...
            figuresFolder, ...
            [scenarios(scenarioIndex).fileName, '.png']));
end

fprintf('MATLAB code:\n%s\n\n', packageCode);

if exist(zipFile, 'file')
    fprintf('ZIP file:\n%s\n\n', zipFile);
end

fprintf('============================================================\n');

end


function summary = simulate_observed_summary( ...
    numberOfClusters, Rp, Rs, ks, pObs, Ip, Is)

primaryCounts = ...
    geornd(1 / Rp, numberOfClusters, 1) + 1;

secondaryCounts = simulate_secondary_totals( ...
    numberOfClusters, primaryCounts, Rs, ks);

primaryPositive = binornd(primaryCounts, Ip);
primaryNegative = primaryCounts - primaryPositive;

secondaryPositive = binornd(secondaryCounts, Is);
secondaryNegative = secondaryCounts - secondaryPositive;

observedPrimaryPositive = ...
    binornd(primaryPositive, pObs);

observedPrimaryNegative = ...
    binornd(primaryNegative, pObs);

observedSecondaryPositive = ...
    binornd(secondaryPositive, pObs);

observedSecondaryNegative = ...
    binornd(secondaryNegative, pObs);

observedPrimaryTotal = ...
    observedPrimaryPositive + observedPrimaryNegative;

observedSecondaryTotal = ...
    observedSecondaryPositive + observedSecondaryNegative;

observedTotalByCluster = ...
    observedPrimaryTotal + observedSecondaryTotal;

nonemptyClusters = observedTotalByCluster > 0;
totalObserved = sum(observedTotalByCluster);

if totalObserved == 0

    summary.totalObserved = 0;
    summary.naiveRs = NaN;
    summary.naiveOR = NaN;
    summary.primaryPositive = NaN;
    summary.primaryNegative = NaN;
    summary.secondaryPositive = NaN;
    summary.secondaryNegative = NaN;

    return;
end

classifiedPrimaryPositive = ...
    zeros(numberOfClusters, 1);

classifiedPrimaryNegative = ...
    zeros(numberOfClusters, 1);

hasObservedPrimary = observedPrimaryTotal > 0;
probabilityPositive = zeros(numberOfClusters, 1);

probabilityPositive(hasObservedPrimary) = ...
    observedPrimaryPositive(hasObservedPrimary) ./ ...
    observedPrimaryTotal(hasObservedPrimary);

classifiedPrimaryPositive(hasObservedPrimary) = ...
    rand(sum(hasObservedPrimary), 1) < ...
    probabilityPositive(hasObservedPrimary);

classifiedPrimaryNegative(hasObservedPrimary) = ...
    1 - classifiedPrimaryPositive(hasObservedPrimary);

hasOnlyObservedSecondary = ...
    (~hasObservedPrimary) & ...
    (observedSecondaryTotal > 0);

probabilityPositive(:) = 0;

probabilityPositive(hasOnlyObservedSecondary) = ...
    observedSecondaryPositive(hasOnlyObservedSecondary) ./ ...
    observedSecondaryTotal(hasOnlyObservedSecondary);

classifiedPrimaryPositive(hasOnlyObservedSecondary) = ...
    rand(sum(hasOnlyObservedSecondary), 1) < ...
    probabilityPositive(hasOnlyObservedSecondary);

classifiedPrimaryNegative(hasOnlyObservedSecondary) = ...
    1 - classifiedPrimaryPositive(hasOnlyObservedSecondary);

QpPositive = ...
    sum(classifiedPrimaryPositive(nonemptyClusters));

QpNegative = ...
    sum(classifiedPrimaryNegative(nonemptyClusters));

totalPositive = sum( ...
    observedPrimaryPositive + observedSecondaryPositive);

totalNegative = sum( ...
    observedPrimaryNegative + observedSecondaryNegative);

QsPositive = totalPositive - QpPositive;
QsNegative = totalNegative - QpNegative;

naiveRs = ...
    (QsPositive + QsNegative) / totalObserved;

a = QpPositive;
b = QpNegative;
c = QsPositive;
d = QsNegative;

naiveOR = ...
    ((a + 0.5) * (d + 0.5)) / ...
    ((b + 0.5) * (c + 0.5));

summary.totalObserved = totalObserved;
summary.naiveRs = naiveRs;
summary.naiveOR = naiveOR;
summary.primaryPositive = QpPositive;
summary.primaryNegative = QpNegative;
summary.secondaryPositive = QsPositive;
summary.secondaryNegative = QsNegative;

end


function totalSecondary = simulate_secondary_totals( ...
    numberOfClusters, primaryCounts, Rs, ks)

totalSecondary = zeros(numberOfClusters, 1);
activeGeneration = primaryCounts;

maximumGeneration = 10000;
generation = 0;

while any(activeGeneration > 0)

    generation = generation + 1;

    if generation > maximumGeneration
        warning('Maximum generation limit reached.');
        break;
    end

    activeIndex = activeGeneration > 0;

    shape = activeGeneration(activeIndex) * ks;
    scale = Rs / ks;

    lambda = gamrnd(shape, scale);
    newCases = poissrnd(lambda);

    activeGeneration(:) = 0;
    activeGeneration(activeIndex) = newCases;

    totalSecondary = totalSecondary + activeGeneration;
end

end


function lookup = precompute_analytical_lookup( ...
    iMax, Rp, ks, pObs, rsGrid, precomputation)

[Cpp, Cps] = primary_classifier_probabilities( ...
    iMax, Rp, pObs);

CspGrid = NaN(size(rsGrid));
CssGrid = NaN(size(rsGrid));
observedRsGrid = NaN(size(rsGrid));

for gridIndex = 1:numel(rsGrid)

    rs = rsGrid(gridIndex);

    [Csp, Css] = secondary_classifier_probabilities( ...
        precomputation, Rp, rs, ks, pObs);

    CspGrid(gridIndex) = Csp;
    CssGrid(gridIndex) = Css;

    observedRsGrid(gridIndex) = ...
        ((1 - rs) * Cps + rs * Css) / pObs;
end

if any(~isfinite(observedRsGrid))
    error('The analytical lookup contains nonfinite values.');
end

[observedRsSorted, sortIndex] = sort(observedRsGrid);
rsSorted = rsGrid(sortIndex);

[observedRsUnique, uniqueIndex] = ...
    unique(observedRsSorted);

rsUnique = rsSorted(uniqueIndex);

lookup.Cpp = Cpp;
lookup.Cps = Cps;
lookup.rsGrid = rsGrid;
lookup.CspGrid = CspGrid;
lookup.CssGrid = CssGrid;
lookup.observedRsUnique = observedRsUnique;
lookup.rsUnique = rsUnique;

end


function correctedRs = infer_corrected_Rs( ...
    observedRs, lookup)

minimumObservedRs = min(lookup.observedRsUnique);
maximumObservedRs = max(lookup.observedRsUnique);

boundedObservedRs = min( ...
    max(observedRs, minimumObservedRs), ...
    maximumObservedRs);

correctedRs = interp1( ...
    lookup.observedRsUnique, ...
    lookup.rsUnique, ...
    boundedObservedRs, ...
    'linear');

end


function precomputation = ...
    make_secondary_precomputation(iMax, ks)

[I, N] = ndgrid(1:iMax, 1:iMax);

validMask = N > I;
base = NaN(iMax, iMax);

base(validMask) = ...
    log(I(validMask)) ...
    - log(N(validMask)) ...
    + gammaln( ...
        ks * N(validMask) + ...
        N(validMask) - ...
        I(validMask)) ...
    - gammaln( ...
        N(validMask) - ...
        I(validMask) + 1) ...
    - gammaln(ks * N(validMask));

precomputation.iMax = iMax;
precomputation.mask = validMask;
precomputation.base = base;
precomputation.nMinusI = N - I;
precomputation.coefficient = ks * N + N - I;

end


function [Csp, Css] = ...
    secondary_classifier_probabilities( ...
    precomputation, Rp, Rs, ks, pObs)

iMax = precomputation.iMax;
iValues = 1:iMax;

clusterSizeProbability = zeros(iMax, iMax);

logProbability = ...
    precomputation.base ...
    + precomputation.nMinusI .* log(Rs / ks) ...
    - precomputation.coefficient .* ...
    log(1 + Rs / ks);

clusterSizeProbability(precomputation.mask) = ...
    exp(logProbability(precomputation.mask));

primaryCountProbability = ...
    (1 - 1 / Rp).^(iValues - 1) / Rp;

weightedProbability = ...
    clusterSizeProbability .* ...
    primaryCountProbability(:);

rightCumulativeSum = ...
    fliplr(cumsum(fliplr(weightedProbability), 2));

topRightSum = cumsum(rightCumulativeSum, 1);

secondaryPositionProbability = zeros(1, iMax);

linearIndex = sub2ind( ...
    [iMax, iMax], ...
    1:(iMax - 1), ...
    2:iMax);

secondaryPositionProbability(2:iMax) = ...
    topRightSum(linearIndex);

secondaryPositionProbability = ...
    secondaryPositionProbability * ...
    (1 - Rs) / Rp / Rs;

if pObs == 1

    Csp = 0;

else

    Csp = sum( ...
        secondaryPositionProbability .* ...
        pObs .* ...
        exp(log(1 - pObs) .* (iValues - 1)));
end

Css = pObs - Csp;

end


function [Cpp, Cps] = ...
    primary_classifier_probabilities( ...
    iMax, Rp, pObs)

iValues = 1:iMax;

primaryCountProbability = ...
    (1 - 1 / Rp).^(iValues - 1) / Rp;

temporarySum = ...
    (1 / Rp) * ...
    cumsum(primaryCountProbability(end:-1:1));

primaryPositionProbability = ...
    temporarySum(end:-1:1);

if pObs == 1

    Cpp = primaryPositionProbability(1);

else

    Cpp = sum( ...
        primaryPositionProbability .* ...
        pObs .* ...
        exp(log(1 - pObs) .* (iValues - 1)));
end

Cps = pObs - Cpp;

end


function trueProbabilities = recover_true_probabilities( ...
    pObs, Cpp, Cps, Csp, Css, ...
    Xpn, Xpp, Xsn, Xsp)

Qpn = ...
    pObs * (Xsn * Csp - Xpn * Css) / ...
    (Cps * Csp - Cpp * Css);

Qpp = ...
    pObs * (Xsp * Csp - Xpp * Css) / ...
    (Cps * Csp - Cpp * Css);

Qsn = ...
    pObs * (Xsn - Xpn * Cps / Cpp) / ...
    (Css - Csp * Cps / Cpp);

Qsp = ...
    pObs * (Xsp - Xpp * Cps / Cpp) / ...
    (Css - Csp * Cps / Cpp);

trueProbabilities = [Qpn, Qpp, Qsn, Qsp];

end


function output = row_percentile( ...
    inputMatrix, percentileValue)

numberOfRows = size(inputMatrix, 1);
output = NaN(numberOfRows, 1);

for rowIndex = 1:numberOfRows

    values = inputMatrix(rowIndex, :);
    values = values(isfinite(values));

    if ~isempty(values)
        output(rowIndex) = ...
            prctile(values, percentileValue);
    end
end

end


function figureHandle = make_scenario_figure( ...
    clusterNumbers, result, Rs, trueOR, scenario)

figureHandle = figure( ...
    'Color', 'w', ...
    'Name', sprintf('Scenario %d', scenario.id), ...
    'Position', [100, 100, 1500, 600]);

leftAxis = subplot(1, 2, 1, ...
    'Parent', figureHandle);

hold(leftAxis, 'on');

fill( ...
    leftAxis, ...
    [clusterNumbers, fliplr(clusterNumbers)], ...
    [ ...
        result.correctedRsLower95(:)', ...
        fliplr(result.correctedRsUpper95(:)')], ...
    [0.8, 0.9, 1], ...
    'EdgeColor', 'none', ...
    'FaceAlpha', 0.75, ...
    'DisplayName', '95% CI (Corrected R_s)');

plot( ...
    leftAxis, ...
    clusterNumbers, ...
    result.medianNaiveRs, ...
    'r-o', ...
    'LineWidth', 2, ...
    'MarkerSize', 6, ...
    'MarkerFaceColor', 'none', ...
    'DisplayName', 'Median R_{obs} (Naive)');

plot( ...
    leftAxis, ...
    clusterNumbers, ...
    result.medianCorrectedRs, ...
    'b-o', ...
    'LineWidth', 2, ...
    'MarkerSize', 6, ...
    'MarkerFaceColor', 'none', ...
    'DisplayName', 'Median Corrected R_s');

plot( ...
    leftAxis, ...
    [clusterNumbers(1), clusterNumbers(end)], ...
    [Rs, Rs], ...
    'k--', ...
    'LineWidth', 2, ...
    'DisplayName', 'True R_s');

set( ...
    leftAxis, ...
    'XScale', 'linear', ...
    'XLim', [100, 1000], ...
    'XTick', clusterNumbers, ...
    'YLim', scenario.RsLimits, ...
    'FontSize', 11);

xlabel(leftAxis, 'Number of Clusters');
ylabel(leftAxis, 'Reproduction Number');

title( ...
    leftAxis, ...
    'Inferred R_s vs. Sample Size', ...
    'Interpreter', 'tex', ...
    'FontWeight', 'bold');

legend(leftAxis, 'show', 'Location', 'best');
grid(leftAxis, 'on');
box(leftAxis, 'on');

hold(leftAxis, 'off');

rightAxis = subplot(1, 2, 2, ...
    'Parent', figureHandle);

hold(rightAxis, 'on');

fill( ...
    rightAxis, ...
    [clusterNumbers, fliplr(clusterNumbers)], ...
    [ ...
        result.correctedORLower95(:)', ...
        fliplr(result.correctedORUpper95(:)')], ...
    [0.8, 0.9, 1], ...
    'EdgeColor', 'none', ...
    'FaceAlpha', 0.75, ...
    'DisplayName', '95% CI (Corrected OR)');

plot( ...
    rightAxis, ...
    clusterNumbers, ...
    result.medianNaiveOR, ...
    'r-o', ...
    'LineWidth', 2, ...
    'MarkerSize', 6, ...
    'MarkerFaceColor', 'none', ...
    'DisplayName', 'Median OR_{obs} (Naive)');

plot( ...
    rightAxis, ...
    clusterNumbers, ...
    result.medianCorrectedOR, ...
    'b-o', ...
    'LineWidth', 2, ...
    'MarkerSize', 6, ...
    'MarkerFaceColor', 'none', ...
    'DisplayName', 'Median Corrected OR');

plot( ...
    rightAxis, ...
    [clusterNumbers(1), clusterNumbers(end)], ...
    [trueOR, trueOR], ...
    'k--', ...
    'LineWidth', 2, ...
    'DisplayName', 'True OR');

set( ...
    rightAxis, ...
    'XScale', 'linear', ...
    'XLim', [100, 1000], ...
    'XTick', clusterNumbers, ...
    'YLim', scenario.ORLimits, ...
    'FontSize', 11);

xlabel(rightAxis, 'Number of Clusters');
ylabel(rightAxis, 'Odds Ratio');

title( ...
    rightAxis, ...
    'Inferred OR vs. Sample Size', ...
    'FontWeight', 'bold');

legend(rightAxis, 'show', 'Location', 'best');
grid(rightAxis, 'on');
box(rightAxis, 'on');

hold(rightAxis, 'off');

end


function create_folder(folderPath)

if ~exist(folderPath, 'dir')

    [success, message] = mkdir(folderPath);

    if ~success
        error('Could not create folder: %s', message);
    end
end

end


function clear_folder_files(folderPath)

items = dir(folderPath);

for itemIndex = 1:numel(items)

    if ~items(itemIndex).isdir

        delete(fullfile( ...
            folderPath, ...
            items(itemIndex).name));
    end
end

end


function save_figure( ...
    figureHandle, pngFile, jpgFile, pdfFile)

drawnow;

try

    exportgraphics( ...
        figureHandle, ...
        pngFile, ...
        'Resolution', 300);

catch

    print( ...
        figureHandle, ...
        pngFile, ...
        '-dpng', ...
        '-r300');
end

try

    exportgraphics( ...
        figureHandle, ...
        jpgFile, ...
        'Resolution', 300);

catch

    print( ...
        figureHandle, ...
        jpgFile, ...
        '-djpeg', ...
        '-r300');
end

try

    exportgraphics( ...
        figureHandle, ...
        pdfFile, ...
        'ContentType', 'vector');

catch

    set(figureHandle, ...
        'PaperPositionMode', 'auto');

    print( ...
        figureHandle, ...
        pdfFile, ...
        '-dpdf', ...
        '-painters', ...
        '-bestfit');
end

end


function write_readme( ...
    readmeFile, ...
    numRuns, ...
    clusterNumbers, ...
    Rs, ...
    ks, ...
    Ip, ...
    Is, ...
    trueOR)

fileID = fopen(readmeFile, 'w');

if fileID == -1
    warning('Could not create README.md.');
    return;
end

fprintf(fileID, ...
    '# Figure S.2 Sample-Size Validation\n\n');

fprintf(fileID, ...
    '## Run\n\n');

fprintf(fileID, ...
    ['Open this folder in MATLAB and run:\n\n', ...
    '```matlab\n', ...
    'generate_figure_S2_sample_size_validation\n', ...
    '```\n\n']);

fprintf(fileID, ...
    '## Requirement\n\n');

fprintf(fileID, ...
    'MATLAB Statistics and Machine Learning Toolbox.\n\n');

fprintf(fileID, ...
    '## Settings\n\n');

fprintf(fileID, '- True R_s: %.2f\n', Rs);
fprintf(fileID, '- Dispersion parameter k_s: %.2f\n', ks);
fprintf(fileID, '- Trait probability I_p: %.4f\n', Ip);
fprintf(fileID, '- Trait probability I_s: %.4f\n', Is);
fprintf(fileID, '- True odds ratio: %.2f\n', trueOR);
fprintf(fileID, '- Simulations per sample size: %d\n', numRuns);

fprintf(fileID, ...
    '- Numbers of clusters: `%s`\n\n', ...
    mat2str(clusterNumbers));

fprintf(fileID, ...
    '## Outputs\n\n');

fprintf(fileID, ...
    ['The `figures` folder contains three separate scenario ', ...
    'figures in PNG, JPG and PDF formats.\n\n']);

fprintf(fileID, ...
    ['The `data` folder contains CSV summaries and ', ...
    'MATLAB result files.\n']);

fclose(fileID);

end